# Generated by Django 4.1.1 on 2023-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher_app', '0002_remove_destination_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
