# Generated by Django 4.1.1 on 2023-06-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher_app', '0003_destination_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='url',
            new_name='Dest_url',
        ),
    ]
