# Generated by Django 4.1.1 on 2023-06-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher_app', '0004_rename_url_destination_dest_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Dest_url',
            new_name='url',
        ),
    ]
